import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { DotBackgroundDemo } from "@/components/ui/grid";
import Header from "@/components/Header";

const inter = Source_Sans_3({ 
  subsets: ["latin"], 
  weight:["400","500","600","700"],
  display:"block"
});

export const metadata: Metadata = {
  title: "Fianchetto - Play Chess Online",
  description: "Generated by npm create convex",
  icons: {
    icon: "/chess-logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      {/* `suppressHydrationWarning` only affects the html tag,
      and is needed by `ThemeProvider` which sets the theme
      class attribute on it */}
      <html  lang="en" suppressHydrationWarning>
        <body className={`dark ${inter.className}`}>
          <DotBackgroundDemo>
          <ConvexClientProvider>
            <ThemeProvider attribute="class">
            
                <Header/>
                {children}
              
            </ThemeProvider>
          </ConvexClientProvider>
          </DotBackgroundDemo>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
